services:
    redis:
        image: "redis:latest"
        ports:
            - '6379:6379'
        container_name: redis
        tty: true
        networks:
            cfp-energy:
                ipv4_address: ${REDIS_HOST}
    webserver:
        image: "nginx:1.17.10"
        container_name: webserver
        ports:
            - '80:80'
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/srv/app
        networks:
            cfp-energy:
                ipv4_address: ${WEBSERVER_HOST}
    php:
        build:
            context: docker/php
            args:
                - USER_ID=1000
                - USER=php
        container_name: php
        working_dir: /srv/app/
        volumes:
            - .:/srv/app/
            - ./docker/php/overrides.conf:/etc/php/8.3/fpm/pool.d/z-overrides.conf
        extra_hosts:
            - host:host-gateway
        networks:
            cfp-energy:
                ipv4_address: ${FPM_HOST}
    database:
        image: "postgres:latest"
        container_name: database
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks:
            cfp-energy:
                ipv4_address: ${DB_HOST}
networks:
    cfp-energy:
        driver: bridge
        ipam:
            config:
                - subnet: ${PROJECT_NETWORK}/24
